#!/bin/sh
if [ $# -eq 0 ]; then
  echo "No arguments supply (try html)"
elif [ $1 == "html" ]; then
  ./scripts/build_html.sh
elif [ $1 == "docx" ]; then
  ./scripts/build_docx.sh
else
  echo "Invalid argument"
fi
